name: Actions workflow

on: []

jobs:
  run-other-actions:
    runs-on: ubuntu latest
    steps:
      - name: A JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Jebin
      - name: Log greeting time
        run: echo "${{steps.greet.outputs.time}}"