name: Shell Commands

on:
  push:
  pull_request: 
    types: [closed, assigned, opened, reopened]

jobs:  
  runs-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Brrruhhhhh"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          chip = platform.processor()
          print(chip)
        shell: python
  run-diff-shells:
    runs-on: windows-latest
    needs: ["runs-shell-command"]
    steps:
      - name: powershell cmd
        run: Get-Location
      - name: bash cmd
        run: pwd
        shell: bash
    